# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1f51ac72b6aa49b68702ed709faccc5154345349b06f10e03be06c152ea12c634e587cfb72c4bbe3ad7d9adc36deb5a165d1fb5cdb1b366b9d7fb499851854d

test:
  secret_key_base: 25e0a7ed67c47212808ec818df4e643c22d44d85a3b0ade59595bac317518ae133f7db762696e8b3a4f8c9b448e171c113875c11fc69646e2b91d82361bdb395

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
